## https://github.com/singularity-data/risingwave/blob/main/src/config/risingwave.toml
apiVersion: v1
data:
  risingwave.toml: |
    [ server ]
    heartbeat_interval = 1000

    [ streaming ]
    checkpoint_interval_ms = 100

    [ storage ]
    sstable_size_mb = 256
    block_size_kb = 16
    bloom_false_positive = 0.1
    share_buffers_sync_parallelism = 2
    shared_buffer_capacity_mb = 1024
    data_directory = "hummock_001"
    write_conflict_detection_enabled = true
    block_cache_capacity_mb = 256
    meta_cache_capacity_mb = 64
    disable_remote_compactor = false
    enable_local_spill = true
    local_object_store = "tempdisk"

kind: ConfigMap
metadata:
  name: {{.NAME}}
  namespace: {{.NAME_SPACE}}