# This file contains all available configuration options
# with their default values (in comments).

# Options for analysis running.
run:
  #  concurrency: 4

  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 5m

  # Which dirs to skip: issues from them won't be reported.
  skip-dirs:
  - pkg/command

  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  # Which files to skip: they will be analyzed, but issues from them won't be reported.
  #  skip-files:
  #    - ".*\\.my\\.go$"
  #    - lib/bad.go

  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: false

  run:
    skip-files:
    - ".*\\_generated.*\\.go$"

# output configuration options
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  format: colored-line-number

  # Print lines of code with issue.
  print-issued-lines: true

  # Print linter name in the end of issue text.
  print-linter-name: true

  # Make issues output unique by line.
  uniq-by-line: true


# All available settings of specific linters.
linters-settings:
  gofmt:
    simplify: false

  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    local-prefixes: github.com/risingwavelabs/risingwave-operator

  revive:
    rules:
    - name: package-comments
      severity: warning
      disabled: true
    - name: exported
      disabled: false
      arguments:
      - "checkPrivateReceivers"
      - "sayRepetitiveInsteadOfStutters"
      - "disableStutteringCheck"
    - name: context-as-argument
      disabled: true
      arguments:
      - allowTypesBefore: "*testing.T, *github.com/risingwavelabs/risingwave-operator/pkg/manager.risingWaveControllerManagerImpl"
    - name: var-naming
      disabled: true
    - name: indent-error-flow

  govet:
    # Settings per analyzer.
    settings:
      # Analyzer name, run `go tool vet help` to see all analyzers.
      printf:
        # Run `go tool vet help printf` to see available settings for `printf` analyzer.
        funcs:
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

    # Enable analyzers by name.
    # Run `go tool vet help` to see all analyzers.
    enable:
    - asmdecl
    - assign
    - atomic
    - atomicalign
    - bools
    - buildtag
    - cgocall
    - composites
    - copylocks
    - deepequalerrors
    - errorsas
    # - fieldalignment
    - findcall
    - framepointer
    - httpresponse
    - ifaceassert
    - loopclosure
    - lostcancel
    - nilfunc
    - nilness
    - nonamedreturns
    - printf
    - reflectvaluecompare
    # - shadow
    - shift
    - sigchanyzer
    - sortslice
    - stdmethods
    - stringintconv
    - structtag
    - testinggoroutine
    - tests
    - unmarshal
    - unreachable
    - unsafeptr
    - unusedresult
    - unusedwrite

  staticcheck:
    go: "1.21"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all" ]

  stylecheck:
    go: "1.21"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]
    # https://staticcheck.io/docs/options#dot_import_whitelist
    dot-import-whitelist:
    - fmt
    # https://staticcheck.io/docs/options#initialisms
    initialisms: [ "ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS" ]
    # https://staticcheck.io/docs/options#http_status_code_whitelist
    http-status-code-whitelist: [ "200", "400", "404", "500" ]


linters:
  disable-all: true
  enable:
  - unused
  - gosimple
  - godot
  - gofmt
  - goimports
  - govet
  - staticcheck
  - stylecheck
  - misspell
  - revive

issues:
  include:
  - EXC0012
  # Fix found issues (if it's supported by the linter).
  fix: false
