apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-manager-config
  namespace: system
data:
  config.yaml: |
    arch: arm64
    default:
      image:
        arm64:
          repository: public.ecr.aws/x5u3w5h6/risingwave-arm
          tag: latest
        amd64:
          repository: ghcr.io/risingwavelabs/risingwave
          tag: latest
      repository: ghcr.io/risingwavelabs/risingwave
      tag: latest
      pullPolicy: Always
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 2000Mi
      replicas: 1
    metaNode:
      requests:
        cpu: 200m
        memory: 1000Mi
      limits:
        cpu: 1000m
        memory: 2000Mi
    computeNode:
      requests:
        cpu: 200m
        memory: 2000Mi
      limits:
        cpu: 1000m
        memory: 2000Mi
    minIO:
      image:
        arm64:
          repository: ghcr.io/risingwavelabs/risingwave-minio
          tag: latest
        amd64:
          repository: ghcr.io/risingwavelabs/risingwave-minio
          tag: latest