apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWave
metadata:
  name: risingwave-component-only
spec:
  storages:
    meta:
      memory: true
    object:
      memory: true
  components:
    meta:
      groups:
      - name: default
        replicas: 1
        image: ghcr.io/risingwavelabs/risingwave:v0.1.17
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
    frontend:
      groups:
      - name: default
        replicas: 1
        image: ghcr.io/risingwavelabs/risingwave:v0.1.17
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
    compute:
      groups:
      - name: default
        replicas: 1
        image: ghcr.io/risingwavelabs/risingwave:v0.1.17
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
    compactor:
      groups:
      - name: default
        replicas: 1
        image: ghcr.io/risingwavelabs/risingwave:v0.1.17
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi