apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWave
metadata:
  name: risingwave-sqlite-s3
spec:
  metaStore:
    sqlite:
      path: /risingwave/data/metastore/risingwave.db
  stateStore:
    dataDirectory: hummock001-directory
    s3:
      bucket: hummock001
      credentials:
        secretName: s3-credentials
        accessKeyRef: AccessKeyID
        secretAccessKeyRef: SecretAccessKey
      region: ap-southeast-1
  image: ghcr.io/risingwavelabs/risingwave:v1.6.0
  components:
    meta:
      nodeGroups:
      - replicas: 1
        name: ""
        volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 20Gi
        template:
          spec:
            volumes:
            - name: heap
              emptyDir:
                sizeLimit: 1Gi
            volumeMounts:
            - mountPath: /heap
              name: heap
            - mountPath: /risingwave/data/metastore
              name: data
              subPath: metastore
            env:
            - name: MALLOC_CONF
              value: prof:true,lg_prof_interval=-1,lg_prof_sample=20,prof_prefix:/heap/
            - name: RW_HEAP_PROFILING_DIR
              value: /heap
            resources:
              limits:
                cpu: 1
                memory: 2Gi
              requests:
                cpu: 1
                memory: 2Gi
    frontend:
      nodeGroups:
      - replicas: 1
        name: ""
        template:
          spec:
            resources:
              limits:
                cpu: 1
                memory: 2Gi
              requests:
                cpu: 1
                memory: 2Gi
    compute:
      nodeGroups:
      - replicas: 1
        name: ""
        template:
          spec:
            volumes:
            - name: heap
              emptyDir:
                sizeLimit: 1Gi
            volumeMounts:
            - mountPath: /heap
              name: heap
            env:
            - name: MALLOC_CONF
              value: prof:true,lg_prof_interval=-1,lg_prof_sample=20,prof_prefix:/heap/
            - name: RW_HEAP_PROFILING_DIR
              value: /heap
            resources:
              limits:
                cpu: 8
                memory: 32Gi # Memory limit will be set to `RW_TOTAL_MEMORY_BYTES`
              requests:
                cpu: 8
                memory: 32Gi
    compactor:
      nodeGroups:
      - replicas: 1
        name: ""
        template:
          spec:
            volumes:
            - name: heap
              emptyDir:
                sizeLimit: 1Gi
            volumeMounts:
            - mountPath: /heap
              name: heap
            env:
            - name: MALLOC_CONF
              value: prof:true,lg_prof_interval=-1,lg_prof_sample=20,prof_prefix:/heap/
            - name: RW_HEAP_PROFILING_DIR
              value: /heap
            resources:
              limits:
                cpu: 4
                memory: 8Gi
              requests:
                cpu: 4
                memory: 8Gi
