apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWave
metadata:
  name: risingwave-spot-toleration
spec:
  storages:
    meta:
      memory: true
    object:
      memory: true
  global:
    image: ghcr.io/risingwavelabs/risingwave:v0.18.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    replicas:
      meta: 1
      frontend: 1
      compute: 1
  components:
    compactor:
      groups:
      - name: spot
        replicas: 1
        tolerations:
        - key: spot
          operator: Exists
          effect: NoSchedule