apiVersion: v1
kind: Secret
metadata: 
  name: risingwave-azure-blob-credentials
stringData:
  AccountName: your-azure-account-name
  AccountKey: your-azure-account-key
---
apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWave
metadata:
  name: risingwave-in-memory-azure-blob
spec:
  metaStore:
    memory: true
  stateStore:
    azureBlob:
      credentials:
        secretName: risingwave-azure-blob-credentials
      container: your-azure-container-name
      root: risingwave
      endpoint: https://your-azure-account-name.blob.core.windows.net
  image: ghcr.io/risingwavelabs/risingwave:git-5cd14918233990d28b48a153fa8d11115089c148
  components:
    meta:
      nodeGroups:
      - replicas: 1
        name: ""
    frontend:
      nodeGroups:
      - replicas: 1
        name: ""
    compute:
      nodeGroups:
      - replicas: 1
        name: ""
    compactor:
      nodeGroups:
      - replicas: 1
        name: ""