apiVersion: v1
kind: Service
metadata:
  name: risingwave-etcd
  labels:
    app: risingwave-etcd
spec:
  ports:
  - port: 2388
    name: client
  - port: 2389
    name: peer
  selector:
    app: risingwave-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: risingwave-etcd
  name: risingwave-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risingwave-etcd
  serviceName: risingwave-etcd
  template:
    metadata:
      labels:
        app: risingwave-etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.4.32
          imagePullPolicy: IfNotPresent
          command:
          - /usr/local/bin/etcd
          args:
          - "--listen-client-urls"
          - "http://0.0.0.0:2388"
          - "--advertise-client-urls"
          - "http://risingwave-etcd-0:2388"
          - "--listen-peer-urls"
          - "http://0.0.0.0:2389"
          - "--initial-advertise-peer-urls"
          - "http://risingwave-etcd-0:2389"
          - "--listen-metrics-urls"
          - "http://0.0.0.0:2379"
          - "--name"
          - "risingwave-etcd"
          - "--max-txn-ops"
          - "999999"
          - "--max-request-bytes"
          - "10485760"
          - "--auto-compaction-mode"
          - periodic
          - "--auto-compaction-retention"
          - 1m
          - "--snapshot-count"
          - "10000"
          env:
          - name: ALLOW_NONE_AUTHENTICATION
            value: "1"
          ports:
          - containerPort: 2389
            name: peer
            protocol: TCP
          - containerPort: 2388
            name: client
            protocol: TCP
---
apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWave
metadata:
  name: risingwave-etcd-s3
spec:
  metaStore:
    etcd:
      endpoint: risingwave-etcd:2388
  stateStore:
    dataDirectory: hummock001-directory
    s3:
      bucket: hummock001
      credentials:
        secretName: s3-credentials
        accessKeyRef: AccessKeyID
        secretAccessKeyRef: SecretAccessKey
      region: ap-southeast-1
  image: risingwavelabs/risingwave:v1.8.4
  components:
    meta:
      nodeGroups:
      - replicas: 1
        name: ""
        template:
          spec:
            volumes:
            - name: heap
              emptyDir:
                sizeLimit: 1Gi
            volumeMounts:
            - mountPath: /heap
              name: heap
            env:
            - name: MALLOC_CONF
              value: prof:true,lg_prof_interval=-1,lg_prof_sample=20,prof_prefix:/heap/
            - name: RW_HEAP_PROFILING_DIR
              value: /heap
            resources:
              limits:
                cpu: 1
                memory: 2Gi
              requests:
                cpu: 1
                memory: 2Gi
    frontend:
      nodeGroups:
      - replicas: 1
        name: ""
        template:
          spec:
            resources:
              limits:
                cpu: 1
                memory: 2Gi
              requests:
                cpu: 1
                memory: 2Gi
    compute:
      nodeGroups:
      - replicas: 1
        name: ""
        template:
          spec:
            volumes:
            - name: heap
              emptyDir:
                sizeLimit: 1Gi
            volumeMounts:
            - mountPath: /heap
              name: heap
            env:
            - name: MALLOC_CONF
              value: prof:true,lg_prof_interval=-1,lg_prof_sample=20,prof_prefix:/heap/
            - name: RW_HEAP_PROFILING_DIR
              value: /heap
            - name: RW_COMPUTE_NODE_ROLE
              value: STREAMING
            resources:
              limits:
                cpu: 8
                memory: 32Gi # Memory limit will be set to `RW_TOTAL_MEMORY_BYTES`
              requests:
                cpu: 8
                memory: 32Gi
      - replicas: 1
        name: "batch"
        template:
          spec:
            volumes:
            - name: heap
              emptyDir:
                sizeLimit: 1Gi
            volumeMounts:
            - mountPath: /heap
              name: heap
            env:
            - name: MALLOC_CONF
              value: prof:true,lg_prof_interval=-1,lg_prof_sample=20,prof_prefix:/heap/
            - name: RW_HEAP_PROFILING_DIR
              value: /heap
            - name: RW_COMPUTE_NODE_ROLE
              value: SERVING
            resources:
              limits:
                cpu: 8
                memory: 32Gi # Memory limit will be set to `RW_TOTAL_MEMORY_BYTES`
              requests:
                cpu: 8
                memory: 32Gi
    compactor:
      nodeGroups:
      - replicas: 1
        name: ""
        template:
          spec:
            volumes:
            - name: heap
              emptyDir:
                sizeLimit: 1Gi
            volumeMounts:
            - mountPath: /heap
              name: heap
            env:
            - name: MALLOC_CONF
              value: prof:true,lg_prof_interval=-1,lg_prof_sample=20,prof_prefix:/heap/
            - name: RW_HEAP_PROFILING_DIR
              value: /heap
            resources:
              limits:
                cpu: 4
                memory: 8Gi
              requests:
                cpu: 4
                memory: 8Gi
