apiVersion: v1
kind: Pod
metadata:
  name: psql-console
spec:
  containers:
  - name: psql
    image: postgres
    imagePullPolicy: IfNotPresent
    command:
    - bash
    args:
    - -c
    - while true; do sleep 10; done
  enableServiceLinks: false