apiVersion: v1
kind: Pod
metadata:
  name: debugger
  namespace: default
spec:
  containers:
  - name: ubuntu-utils
    image: arunvelsriram/utils
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  