prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

# Run `helm show values prometheus-community/kube-prometheus-stack` to get information about the below values
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  additionalServiceMonitors:
  - name: prometheus-service-monitor-rw-operator
    namespaceSelector: 
      matchNames:
      - risingwave-operator-system
    endpoints:
    - interval: 10s
      path: /metrics
      port: http
      scheme: https
      scrapeTimeout: 5s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt # I think I can remove this
        insecureSkipVerify: true
    selector:
      matchLabels: 
        control-plane: controller-manager
  - name: risingwave-service-monitor
    additionalLabels:
      risingwave/name: risingwave
    endpoints:
    - bearerTokenSecret:
        key: ""
      interval: 5s
      metricRelabelings:
        - action: drop
          regex: stream_exchange_.+
          sourceLabels:
            - __name__
      port: metrics
      scrapeTimeout: 5s
    jobLabel: risingwave/risingwave
    namespaceSelector:
      any: true
    selector:
      matchExpressions:
      - key: risingwave/name
        operator: Exists
    targetLabels:
    - risingwave/name
    - risingwave/component
    - risingwave/group

grafana:
  additionalDataSources:
    - name: risedev-prometheus
      url: http://prometheus-kube-prometheus-prometheus:9090/
      type: prometheus
  dashboardProviders:
    rw-dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: risingwave
        orgId: 1
        folder: RisingWave
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/risingwave
  dashboards:
    risingwave:
      risingwave-user-dashboard:
        url: https://raw.githubusercontent.com/risingwavelabs/risingwave/main/grafana/risingwave-user-dashboard.json
      risingwave-dev-dashboard:
        url: https://raw.githubusercontent.com/risingwavelabs/risingwave/main/grafana/risingwave-dev-dashboard.json
