prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  dashboardProviders:
    rw-dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: risingwave
        orgId: 1
        folder: RisingWave
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/risingwave
  dashboards:
    risingwave:
      risingwave-dashboard:
        url: https://raw.githubusercontent.com/singularity-data/risingwave-operator/main/monitoring/grafana/risingwave-dashboard.json