//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright 2023 RisingWave Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/openkruise/kruise-api/apps/pub"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentGroupReplicasStatus) DeepCopyInto(out *ComponentGroupReplicasStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentGroupReplicasStatus.
func (in *ComponentGroupReplicasStatus) DeepCopy() *ComponentGroupReplicasStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentGroupReplicasStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentReplicasStatus) DeepCopyInto(out *ComponentReplicasStatus) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]ComponentGroupReplicasStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentReplicasStatus.
func (in *ComponentReplicasStatus) DeepCopy() *ComponentReplicasStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentReplicasStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaim) DeepCopyInto(out *PersistentVolumeClaim) {
	*out = *in
	in.PersistentVolumeClaimPartialObjectMeta.DeepCopyInto(&out.PersistentVolumeClaimPartialObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaim.
func (in *PersistentVolumeClaim) DeepCopy() *PersistentVolumeClaim {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimPartialObjectMeta) DeepCopyInto(out *PersistentVolumeClaimPartialObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Finalizers != nil {
		in, out := &in.Finalizers, &out.Finalizers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimPartialObjectMeta.
func (in *PersistentVolumeClaimPartialObjectMeta) DeepCopy() *PersistentVolumeClaimPartialObjectMeta {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimPartialObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWave) DeepCopyInto(out *RisingWave) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWave.
func (in *RisingWave) DeepCopy() *RisingWave {
	if in == nil {
		return nil
	}
	out := new(RisingWave)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RisingWave) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveAzureBlobCredentials) DeepCopyInto(out *RisingWaveAzureBlobCredentials) {
	*out = *in
	if in.AccountNameRef != nil {
		in, out := &in.AccountNameRef, &out.AccountNameRef
		*out = new(string)
		**out = **in
	}
	if in.AccountKeyRef != nil {
		in, out := &in.AccountKeyRef, &out.AccountKeyRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveAzureBlobCredentials.
func (in *RisingWaveAzureBlobCredentials) DeepCopy() *RisingWaveAzureBlobCredentials {
	if in == nil {
		return nil
	}
	out := new(RisingWaveAzureBlobCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentCommonPorts) DeepCopyInto(out *RisingWaveComponentCommonPorts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentCommonPorts.
func (in *RisingWaveComponentCommonPorts) DeepCopy() *RisingWaveComponentCommonPorts {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentCommonPorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentCompactor) DeepCopyInto(out *RisingWaveComponentCompactor) {
	*out = *in
	if in.RestartAt != nil {
		in, out := &in.RestartAt, &out.RestartAt
		*out = (*in).DeepCopy()
	}
	out.Ports = in.Ports
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]RisingWaveComponentGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentCompactor.
func (in *RisingWaveComponentCompactor) DeepCopy() *RisingWaveComponentCompactor {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentCompactor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentCompute) DeepCopyInto(out *RisingWaveComponentCompute) {
	*out = *in
	if in.RestartAt != nil {
		in, out := &in.RestartAt, &out.RestartAt
		*out = (*in).DeepCopy()
	}
	out.Ports = in.Ports
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]RisingWaveComputeGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentCompute.
func (in *RisingWaveComponentCompute) DeepCopy() *RisingWaveComponentCompute {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentCompute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentConnector) DeepCopyInto(out *RisingWaveComponentConnector) {
	*out = *in
	if in.RestartAt != nil {
		in, out := &in.RestartAt, &out.RestartAt
		*out = (*in).DeepCopy()
	}
	out.Ports = in.Ports
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]RisingWaveComponentGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentConnector.
func (in *RisingWaveComponentConnector) DeepCopy() *RisingWaveComponentConnector {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentFrontend) DeepCopyInto(out *RisingWaveComponentFrontend) {
	*out = *in
	if in.RestartAt != nil {
		in, out := &in.RestartAt, &out.RestartAt
		*out = (*in).DeepCopy()
	}
	out.Ports = in.Ports
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]RisingWaveComponentGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentFrontend.
func (in *RisingWaveComponentFrontend) DeepCopy() *RisingWaveComponentFrontend {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentFrontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentGroup) DeepCopyInto(out *RisingWaveComponentGroup) {
	*out = *in
	if in.RisingWaveComponentGroupTemplate != nil {
		in, out := &in.RisingWaveComponentGroupTemplate, &out.RisingWaveComponentGroupTemplate
		*out = new(RisingWaveComponentGroupTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentGroup.
func (in *RisingWaveComponentGroup) DeepCopy() *RisingWaveComponentGroup {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentGroupTemplate) DeepCopyInto(out *RisingWaveComponentGroupTemplate) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.UpgradeStrategy.DeepCopyInto(&out.UpgradeStrategy)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(string)
		**out = **in
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(v1.PodDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	in.Metadata.DeepCopyInto(&out.Metadata)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentGroupTemplate.
func (in *RisingWaveComponentGroupTemplate) DeepCopy() *RisingWaveComponentGroupTemplate {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentGroupTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentMeta) DeepCopyInto(out *RisingWaveComponentMeta) {
	*out = *in
	if in.RestartAt != nil {
		in, out := &in.RestartAt, &out.RestartAt
		*out = (*in).DeepCopy()
	}
	out.Ports = in.Ports
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]RisingWaveComponentGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentMeta.
func (in *RisingWaveComponentMeta) DeepCopy() *RisingWaveComponentMeta {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentMetaPorts) DeepCopyInto(out *RisingWaveComponentMetaPorts) {
	*out = *in
	out.RisingWaveComponentCommonPorts = in.RisingWaveComponentCommonPorts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentMetaPorts.
func (in *RisingWaveComponentMetaPorts) DeepCopy() *RisingWaveComponentMetaPorts {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentMetaPorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentsReplicasStatus) DeepCopyInto(out *RisingWaveComponentsReplicasStatus) {
	*out = *in
	in.Meta.DeepCopyInto(&out.Meta)
	in.Frontend.DeepCopyInto(&out.Frontend)
	in.Compute.DeepCopyInto(&out.Compute)
	in.Compactor.DeepCopyInto(&out.Compactor)
	in.Connector.DeepCopyInto(&out.Connector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentsReplicasStatus.
func (in *RisingWaveComponentsReplicasStatus) DeepCopy() *RisingWaveComponentsReplicasStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentsReplicasStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentsSpec) DeepCopyInto(out *RisingWaveComponentsSpec) {
	*out = *in
	in.Meta.DeepCopyInto(&out.Meta)
	in.Frontend.DeepCopyInto(&out.Frontend)
	in.Compute.DeepCopyInto(&out.Compute)
	in.Compactor.DeepCopyInto(&out.Compactor)
	in.Connector.DeepCopyInto(&out.Connector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentsSpec.
func (in *RisingWaveComponentsSpec) DeepCopy() *RisingWaveComponentsSpec {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComputeGroup) DeepCopyInto(out *RisingWaveComputeGroup) {
	*out = *in
	if in.RisingWaveComputeGroupTemplate != nil {
		in, out := &in.RisingWaveComputeGroupTemplate, &out.RisingWaveComputeGroupTemplate
		*out = new(RisingWaveComputeGroupTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComputeGroup.
func (in *RisingWaveComputeGroup) DeepCopy() *RisingWaveComputeGroup {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComputeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComputeGroupTemplate) DeepCopyInto(out *RisingWaveComputeGroupTemplate) {
	*out = *in
	in.RisingWaveComponentGroupTemplate.DeepCopyInto(&out.RisingWaveComponentGroupTemplate)
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComputeGroupTemplate.
func (in *RisingWaveComputeGroupTemplate) DeepCopy() *RisingWaveComputeGroupTemplate {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComputeGroupTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveCondition) DeepCopyInto(out *RisingWaveCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveCondition.
func (in *RisingWaveCondition) DeepCopy() *RisingWaveCondition {
	if in == nil {
		return nil
	}
	out := new(RisingWaveCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveConfigurationSpec) DeepCopyInto(out *RisingWaveConfigurationSpec) {
	*out = *in
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveConfigurationSpec.
func (in *RisingWaveConfigurationSpec) DeepCopy() *RisingWaveConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(RisingWaveConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveEtcdCredentials) DeepCopyInto(out *RisingWaveEtcdCredentials) {
	*out = *in
	if in.UsernameKeyRef != nil {
		in, out := &in.UsernameKeyRef, &out.UsernameKeyRef
		*out = new(string)
		**out = **in
	}
	if in.PasswordKeyRef != nil {
		in, out := &in.PasswordKeyRef, &out.PasswordKeyRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveEtcdCredentials.
func (in *RisingWaveEtcdCredentials) DeepCopy() *RisingWaveEtcdCredentials {
	if in == nil {
		return nil
	}
	out := new(RisingWaveEtcdCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveGCSCredentials) DeepCopyInto(out *RisingWaveGCSCredentials) {
	*out = *in
	if in.ServiceAccountCredentialsKeyRef != nil {
		in, out := &in.ServiceAccountCredentialsKeyRef, &out.ServiceAccountCredentialsKeyRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveGCSCredentials.
func (in *RisingWaveGCSCredentials) DeepCopy() *RisingWaveGCSCredentials {
	if in == nil {
		return nil
	}
	out := new(RisingWaveGCSCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveGlobalReplicas) DeepCopyInto(out *RisingWaveGlobalReplicas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveGlobalReplicas.
func (in *RisingWaveGlobalReplicas) DeepCopy() *RisingWaveGlobalReplicas {
	if in == nil {
		return nil
	}
	out := new(RisingWaveGlobalReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveGlobalSpec) DeepCopyInto(out *RisingWaveGlobalSpec) {
	*out = *in
	in.RisingWaveComponentGroupTemplate.DeepCopyInto(&out.RisingWaveComponentGroupTemplate)
	out.Replicas = in.Replicas
	in.ServiceMeta.DeepCopyInto(&out.ServiceMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveGlobalSpec.
func (in *RisingWaveGlobalSpec) DeepCopy() *RisingWaveGlobalSpec {
	if in == nil {
		return nil
	}
	out := new(RisingWaveGlobalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveList) DeepCopyInto(out *RisingWaveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RisingWave, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveList.
func (in *RisingWaveList) DeepCopy() *RisingWaveList {
	if in == nil {
		return nil
	}
	out := new(RisingWaveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RisingWaveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveMetaStoreBackend) DeepCopyInto(out *RisingWaveMetaStoreBackend) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(bool)
		**out = **in
	}
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(RisingWaveMetaStoreBackendEtcd)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveMetaStoreBackend.
func (in *RisingWaveMetaStoreBackend) DeepCopy() *RisingWaveMetaStoreBackend {
	if in == nil {
		return nil
	}
	out := new(RisingWaveMetaStoreBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveMetaStoreBackendEtcd) DeepCopyInto(out *RisingWaveMetaStoreBackendEtcd) {
	*out = *in
	if in.RisingWaveEtcdCredentials != nil {
		in, out := &in.RisingWaveEtcdCredentials, &out.RisingWaveEtcdCredentials
		*out = new(RisingWaveEtcdCredentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveMetaStoreBackendEtcd.
func (in *RisingWaveMetaStoreBackendEtcd) DeepCopy() *RisingWaveMetaStoreBackendEtcd {
	if in == nil {
		return nil
	}
	out := new(RisingWaveMetaStoreBackendEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveMetaStoreStatus) DeepCopyInto(out *RisingWaveMetaStoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveMetaStoreStatus.
func (in *RisingWaveMetaStoreStatus) DeepCopy() *RisingWaveMetaStoreStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveMetaStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveMinIOCredentials) DeepCopyInto(out *RisingWaveMinIOCredentials) {
	*out = *in
	if in.UsernameKeyRef != nil {
		in, out := &in.UsernameKeyRef, &out.UsernameKeyRef
		*out = new(string)
		**out = **in
	}
	if in.PasswordKeyRef != nil {
		in, out := &in.PasswordKeyRef, &out.PasswordKeyRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveMinIOCredentials.
func (in *RisingWaveMinIOCredentials) DeepCopy() *RisingWaveMinIOCredentials {
	if in == nil {
		return nil
	}
	out := new(RisingWaveMinIOCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWavePodTemplate) DeepCopyInto(out *RisingWavePodTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWavePodTemplate.
func (in *RisingWavePodTemplate) DeepCopy() *RisingWavePodTemplate {
	if in == nil {
		return nil
	}
	out := new(RisingWavePodTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RisingWavePodTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWavePodTemplateList) DeepCopyInto(out *RisingWavePodTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RisingWavePodTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWavePodTemplateList.
func (in *RisingWavePodTemplateList) DeepCopy() *RisingWavePodTemplateList {
	if in == nil {
		return nil
	}
	out := new(RisingWavePodTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RisingWavePodTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWavePodTemplatePartialObjectMeta) DeepCopyInto(out *RisingWavePodTemplatePartialObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWavePodTemplatePartialObjectMeta.
func (in *RisingWavePodTemplatePartialObjectMeta) DeepCopy() *RisingWavePodTemplatePartialObjectMeta {
	if in == nil {
		return nil
	}
	out := new(RisingWavePodTemplatePartialObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWavePodTemplateSpec) DeepCopyInto(out *RisingWavePodTemplateSpec) {
	*out = *in
	in.RisingWavePodTemplatePartialObjectMeta.DeepCopyInto(&out.RisingWavePodTemplatePartialObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWavePodTemplateSpec.
func (in *RisingWavePodTemplateSpec) DeepCopy() *RisingWavePodTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(RisingWavePodTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveRollingUpdate) DeepCopyInto(out *RisingWaveRollingUpdate) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Partition != nil {
		in, out := &in.Partition, &out.Partition
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveRollingUpdate.
func (in *RisingWaveRollingUpdate) DeepCopy() *RisingWaveRollingUpdate {
	if in == nil {
		return nil
	}
	out := new(RisingWaveRollingUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveS3Credentials) DeepCopyInto(out *RisingWaveS3Credentials) {
	*out = *in
	if in.AccessKeyRef != nil {
		in, out := &in.AccessKeyRef, &out.AccessKeyRef
		*out = new(string)
		**out = **in
	}
	if in.SecretAccessKeyRef != nil {
		in, out := &in.SecretAccessKeyRef, &out.SecretAccessKeyRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveS3Credentials.
func (in *RisingWaveS3Credentials) DeepCopy() *RisingWaveS3Credentials {
	if in == nil {
		return nil
	}
	out := new(RisingWaveS3Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleView) DeepCopyInto(out *RisingWaveScaleView) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleView.
func (in *RisingWaveScaleView) DeepCopy() *RisingWaveScaleView {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleView)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RisingWaveScaleView) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewList) DeepCopyInto(out *RisingWaveScaleViewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RisingWaveScaleView, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewList.
func (in *RisingWaveScaleViewList) DeepCopy() *RisingWaveScaleViewList {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RisingWaveScaleViewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewLock) DeepCopyInto(out *RisingWaveScaleViewLock) {
	*out = *in
	if in.GroupLocks != nil {
		in, out := &in.GroupLocks, &out.GroupLocks
		*out = make([]RisingWaveScaleViewLockGroupLock, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewLock.
func (in *RisingWaveScaleViewLock) DeepCopy() *RisingWaveScaleViewLock {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewLock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewLockGroupLock) DeepCopyInto(out *RisingWaveScaleViewLockGroupLock) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewLockGroupLock.
func (in *RisingWaveScaleViewLockGroupLock) DeepCopy() *RisingWaveScaleViewLockGroupLock {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewLockGroupLock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewSpec) DeepCopyInto(out *RisingWaveScaleViewSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ScalePolicy != nil {
		in, out := &in.ScalePolicy, &out.ScalePolicy
		*out = make([]RisingWaveScaleViewSpecScalePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewSpec.
func (in *RisingWaveScaleViewSpec) DeepCopy() *RisingWaveScaleViewSpec {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewSpecScalePolicy) DeepCopyInto(out *RisingWaveScaleViewSpecScalePolicy) {
	*out = *in
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewSpecScalePolicy.
func (in *RisingWaveScaleViewSpecScalePolicy) DeepCopy() *RisingWaveScaleViewSpecScalePolicy {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewSpecScalePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewSpecScalePolicyConstraints) DeepCopyInto(out *RisingWaveScaleViewSpecScalePolicyConstraints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewSpecScalePolicyConstraints.
func (in *RisingWaveScaleViewSpecScalePolicyConstraints) DeepCopy() *RisingWaveScaleViewSpecScalePolicyConstraints {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewSpecScalePolicyConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewStatus) DeepCopyInto(out *RisingWaveScaleViewStatus) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewStatus.
func (in *RisingWaveScaleViewStatus) DeepCopy() *RisingWaveScaleViewStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewTargetRef) DeepCopyInto(out *RisingWaveScaleViewTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewTargetRef.
func (in *RisingWaveScaleViewTargetRef) DeepCopy() *RisingWaveScaleViewTargetRef {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveSpec) DeepCopyInto(out *RisingWaveSpec) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
	in.Storages.DeepCopyInto(&out.Storages)
	in.Components.DeepCopyInto(&out.Components)
	in.Configuration.DeepCopyInto(&out.Configuration)
	if in.EnableOpenKruise != nil {
		in, out := &in.EnableOpenKruise, &out.EnableOpenKruise
		*out = new(bool)
		**out = **in
	}
	if in.EnableDefaultServiceMonitor != nil {
		in, out := &in.EnableDefaultServiceMonitor, &out.EnableDefaultServiceMonitor
		*out = new(bool)
		**out = **in
	}
	in.AdditionalFrontendServiceMetadata.DeepCopyInto(&out.AdditionalFrontendServiceMetadata)
	in.MetaStore.DeepCopyInto(&out.MetaStore)
	in.StateStore.DeepCopyInto(&out.StateStore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveSpec.
func (in *RisingWaveSpec) DeepCopy() *RisingWaveSpec {
	if in == nil {
		return nil
	}
	out := new(RisingWaveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackend) DeepCopyInto(out *RisingWaveStateStoreBackend) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(bool)
		**out = **in
	}
	if in.MinIO != nil {
		in, out := &in.MinIO, &out.MinIO
		*out = new(RisingWaveStateStoreBackendMinIO)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(RisingWaveStateStoreBackendS3)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(RisingWaveStateStoreBackendGCS)
		(*in).DeepCopyInto(*out)
	}
	if in.AliyunOSS != nil {
		in, out := &in.AliyunOSS, &out.AliyunOSS
		*out = new(RisingWaveStateStoreBackendAliyunOSS)
		(*in).DeepCopyInto(*out)
	}
	if in.AzureBlob != nil {
		in, out := &in.AzureBlob, &out.AzureBlob
		*out = new(RisingWaveStateStoreBackendAzureBlob)
		(*in).DeepCopyInto(*out)
	}
	if in.HDFS != nil {
		in, out := &in.HDFS, &out.HDFS
		*out = new(RisingWaveStateStoreBackendHDFS)
		**out = **in
	}
	if in.WebHDFS != nil {
		in, out := &in.WebHDFS, &out.WebHDFS
		*out = new(RisingWaveStateStoreBackendHDFS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackend.
func (in *RisingWaveStateStoreBackend) DeepCopy() *RisingWaveStateStoreBackend {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendAliyunOSS) DeepCopyInto(out *RisingWaveStateStoreBackendAliyunOSS) {
	*out = *in
	in.RisingWaveS3Credentials.DeepCopyInto(&out.RisingWaveS3Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendAliyunOSS.
func (in *RisingWaveStateStoreBackendAliyunOSS) DeepCopy() *RisingWaveStateStoreBackendAliyunOSS {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendAliyunOSS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendAzureBlob) DeepCopyInto(out *RisingWaveStateStoreBackendAzureBlob) {
	*out = *in
	in.RisingWaveAzureBlobCredentials.DeepCopyInto(&out.RisingWaveAzureBlobCredentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendAzureBlob.
func (in *RisingWaveStateStoreBackendAzureBlob) DeepCopy() *RisingWaveStateStoreBackendAzureBlob {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendAzureBlob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendGCS) DeepCopyInto(out *RisingWaveStateStoreBackendGCS) {
	*out = *in
	in.RisingWaveGCSCredentials.DeepCopyInto(&out.RisingWaveGCSCredentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendGCS.
func (in *RisingWaveStateStoreBackendGCS) DeepCopy() *RisingWaveStateStoreBackendGCS {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendGCS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendHDFS) DeepCopyInto(out *RisingWaveStateStoreBackendHDFS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendHDFS.
func (in *RisingWaveStateStoreBackendHDFS) DeepCopy() *RisingWaveStateStoreBackendHDFS {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendHDFS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendMinIO) DeepCopyInto(out *RisingWaveStateStoreBackendMinIO) {
	*out = *in
	in.RisingWaveMinIOCredentials.DeepCopyInto(&out.RisingWaveMinIOCredentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendMinIO.
func (in *RisingWaveStateStoreBackendMinIO) DeepCopy() *RisingWaveStateStoreBackendMinIO {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendMinIO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendS3) DeepCopyInto(out *RisingWaveStateStoreBackendS3) {
	*out = *in
	in.RisingWaveS3Credentials.DeepCopyInto(&out.RisingWaveS3Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendS3.
func (in *RisingWaveStateStoreBackendS3) DeepCopy() *RisingWaveStateStoreBackendS3 {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendS3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreStatus) DeepCopyInto(out *RisingWaveStateStoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreStatus.
func (in *RisingWaveStateStoreStatus) DeepCopy() *RisingWaveStateStoreStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStatus) DeepCopyInto(out *RisingWaveStatus) {
	*out = *in
	in.ComponentReplicas.DeepCopyInto(&out.ComponentReplicas)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]RisingWaveCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScaleViews != nil {
		in, out := &in.ScaleViews, &out.ScaleViews
		*out = make([]RisingWaveScaleViewLock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.MetaStore = in.MetaStore
	out.StateStore = in.StateStore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStatus.
func (in *RisingWaveStatus) DeepCopy() *RisingWaveStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStoragesSpec) DeepCopyInto(out *RisingWaveStoragesSpec) {
	*out = *in
	in.Meta.DeepCopyInto(&out.Meta)
	in.Object.DeepCopyInto(&out.Object)
	if in.PVCTemplates != nil {
		in, out := &in.PVCTemplates, &out.PVCTemplates
		*out = make([]PersistentVolumeClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStoragesSpec.
func (in *RisingWaveStoragesSpec) DeepCopy() *RisingWaveStoragesSpec {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStoragesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStoragesStatus) DeepCopyInto(out *RisingWaveStoragesStatus) {
	*out = *in
	out.Meta = in.Meta
	out.Object = in.Object
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStoragesStatus.
func (in *RisingWaveStoragesStatus) DeepCopy() *RisingWaveStoragesStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStoragesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveUpgradeStrategy) DeepCopyInto(out *RisingWaveUpgradeStrategy) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RisingWaveRollingUpdate)
		(*in).DeepCopyInto(*out)
	}
	if in.InPlaceUpdateStrategy != nil {
		in, out := &in.InPlaceUpdateStrategy, &out.InPlaceUpdateStrategy
		*out = new(pub.InPlaceUpdateStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveUpgradeStrategy.
func (in *RisingWaveUpgradeStrategy) DeepCopy() *RisingWaveUpgradeStrategy {
	if in == nil {
		return nil
	}
	out := new(RisingWaveUpgradeStrategy)
	in.DeepCopyInto(out)
	return out
}
