apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWavePodTemplate
metadata:
  name: privileged
template:
  metadata:
    labels:
      risingwave/privileged: "1"
  spec:
    containers:
    - name: ""
      securityContext:
        privileged: true
---
apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWave
metadata:
  name: risingwave-privileged
spec:
  storages:
    meta:
      memory: true
    object:
      memory: true
  global:
    image: ghcr.io/risingwavelabs/risingwave:latest
    # image: public.ecr.aws/x5u3w5h6/risingwave-arm:latest
    imagePullPolicy: IfNotPresent
    podTemplate: privileged
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    replicas:
      meta: 1
      frontend: 1
      compute: 1
      compactor: 1