apiVersion: v1
kind: Service
metadata:
  name: risingwave-etcd
  labels:
    app: risingwave-etcd
spec:
  ports:
  - port: 2388
    name: client
  - port: 2389
    name: peer
  selector:
    app: risingwave-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: risingwave-etcd
  name: risingwave-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risingwave-etcd
  serviceName: risingwave-etcd
  template:
    metadata:
      labels:
        app: risingwave-etcd
    spec:
      enableServiceLinks: false
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - export ETCDCTL_API=3; while ! etcdctl --endpoints http://risingwave-etcd-0:2388 user list > /dev/null; do sleep 2; done ; echo 123456 | etcdctl --endpoints http://risingwave-etcd-0:2388 user add root --interactive=false; etcdctl --user root:123456 --endpoints http://risingwave-etcd-0:2388 auth enable
        command:
        - /usr/local/bin/etcd
        args:
        - "--listen-client-urls"
        - "http://0.0.0.0:2388"
        - "--advertise-client-urls"
        - "http://risingwave-etcd-0:2388"
        - "--listen-peer-urls"
        - "http://0.0.0.0:2389"
        - "--initial-advertise-peer-urls"
        - "http://risingwave-etcd-0:2389"
        - "--listen-metrics-urls"
        - "http://0.0.0.0:2379"
        - "--name"
        - "risingwave-etcd"
        - "--max-txn-ops"
        - "999999"
        - "--auto-compaction-mode"
        - periodic
        - "--auto-compaction-retention"
        - 1m
        - "--snapshot-count"
        - "10000"
        ports:
        - containerPort: 2389
          name: peer
          protocol: TCP
        - containerPort: 2388
          name: client
          protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-credentials
stringData:
  username: root
  password: "123456"
---
apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWave
metadata:
  name: risingwave-etcd-auth
spec:
  storages:
    meta:
      etcd:
        endpoint: risingwave-etcd:2388
        secret: etcd-credentials
    object:
      memory: true
  global:
    image: ghcr.io/risingwavelabs/risingwave:latest
    # image: public.ecr.aws/x5u3w5h6/risingwave-arm:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    replicas:
      meta: 1
      frontend: 1
      compute: 1
      compactor: 1