apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWaveScaleView
metadata:
  name: hello-frontend-scale-view
spec:
  targetRef:
    name: hello
    component: frontend
  replicas: 10
  scalePolicy:
  - group: 'enduring'
    priority: 1
    constraints:
      min: 1
      max: 2
  - group: 'spot'
    replicas: 3