apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWave
metadata:
  name: e2e-scale-view
spec:
  storages:
    meta:
      memory: true
    object:
      memory: true
  global:
    image: ghcr.io/risingwavelabs/risingwave:e2e
    replicas:
      meta: 1
      compute: 1
  components:
    frontend:
      groups:
      - name: group-0
        replicas: 1
      - name: group-1
        replicas: 2
    compactor:
      groups:
      - name: group-0
        replicas: 1
      - name: group-1
        replicas: 0
---
apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWaveScaleView
metadata:
  name: e2e-sv-compact
  labels:
    e2e/component: compactor
spec:
  targetRef:
    name: e2e-scale-view
    component: compactor
  scalePolicy:
  - group: group-0
    priority: 1
    maxReplicas: 2
  - group: group-1
---
apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWaveScaleView
metadata:
  name: e2e-sv-frontend
  labels:
    e2e/component: frontend
spec:
  targetRef:
    name: e2e-scale-view
    component: frontend