apiVersion: v1
kind: Pod
metadata:
  name: network-utils
spec:
  containers:
  - image: praqma/network-multitool
    imagePullPolicy: IfNotPresent
    name: network-utils
    command:
    - bash
    args:
    - -c
    - while true; do sleep 10; done
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory