apiVersion: risingwave.singularity-data.com/v1alpha1
kind: RisingWave
metadata:
  name: risingwave-in-memory
spec:
  storages:
    meta:
      memory: true
    object:
      memory: true
  global:
    image: ghcr.io/singularity-data/risingwave:e2e
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    replicas:
      meta: 1
      frontend: 1
      compute: 1
      compactor: 1