//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright 2022 Singularity Data
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by ctrlkit. DO NOT EDIT.

package manager

import (
	"context"
	"fmt"

	"github.com/go-logr/logr"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	risingwavev1alpha1 "github.com/risingwavelabs/risingwave-operator/apis/risingwave/v1alpha1"
	"github.com/risingwavelabs/risingwave-operator/pkg/ctrlkit"
)

// RisingWaveScaleViewControllerManagerState is the state manager of RisingWaveScaleViewControllerManager.
type RisingWaveScaleViewControllerManagerState struct {
	client.Reader
	target *risingwavev1alpha1.RisingWaveScaleView
}

// GetTargetObj gets targetObj with name equals to ${target.Spec.TargetRef.Name}.
func (s *RisingWaveScaleViewControllerManagerState) GetTargetObj(ctx context.Context) (*risingwavev1alpha1.RisingWave, error) {
	var targetObj risingwavev1alpha1.RisingWave

	err := s.Get(ctx, types.NamespacedName{
		Namespace: s.target.Namespace,
		Name:      s.target.Spec.TargetRef.Name,
	}, &targetObj)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("unable to get state 'targetObj': %w", err)
	}

	return &targetObj, nil
}

// NewRisingWaveScaleViewControllerManagerState returns a RisingWaveScaleViewControllerManagerState (target is not copied).
func NewRisingWaveScaleViewControllerManagerState(reader client.Reader, target *risingwavev1alpha1.RisingWaveScaleView) RisingWaveScaleViewControllerManagerState {
	return RisingWaveScaleViewControllerManagerState{
		Reader: reader,
		target: target,
	}
}

// RisingWaveScaleViewControllerManagerImpl declares the implementation interface for RisingWaveScaleViewControllerManager.
type RisingWaveScaleViewControllerManagerImpl interface {
	// Grab the lock for the current RisingWaveScaleView.
	GrabScaleViewLock(ctx context.Context, logger logr.Logger, targetObj *risingwavev1alpha1.RisingWave) (ctrl.Result, error)

	// Sync the replicas of targeting groups to RisingWave's spec.
	SyncGroupReplicasToRisingWave(ctx context.Context, logger logr.Logger, targetObj *risingwavev1alpha1.RisingWave) (ctrl.Result, error)

	// Sync the replicas from RisingWave's spec.
	SyncGroupReplicasStatusFromRisingWave(ctx context.Context, logger logr.Logger, targetObj *risingwavev1alpha1.RisingWave) (ctrl.Result, error)

	// Handle the finalizer.
	HandleScaleViewFinalizer(ctx context.Context, logger logr.Logger, targetObj *risingwavev1alpha1.RisingWave) (ctrl.Result, error)
}

// Pre-defined actions in RisingWaveScaleViewControllerManager.
const (
	RisingWaveScaleViewAction_GrabScaleViewLock                     = "GrabScaleViewLock"
	RisingWaveScaleViewAction_SyncGroupReplicasToRisingWave         = "SyncGroupReplicasToRisingWave"
	RisingWaveScaleViewAction_SyncGroupReplicasStatusFromRisingWave = "SyncGroupReplicasStatusFromRisingWave"
	RisingWaveScaleViewAction_HandleScaleViewFinalizer              = "HandleScaleViewFinalizer"
)

// RisingWaveScaleViewControllerManager encapsulates the states and actions used by RisingWaveScaleViewController.
type RisingWaveScaleViewControllerManager struct {
	hook   ctrlkit.ActionHook
	state  RisingWaveScaleViewControllerManagerState
	impl   RisingWaveScaleViewControllerManagerImpl
	logger logr.Logger
}

// NewAction returns a new action controlled by the manager.
func (m *RisingWaveScaleViewControllerManager) NewAction(description string, f func(context.Context, logr.Logger) (ctrl.Result, error)) ctrlkit.Action {
	return ctrlkit.NewAction(description, func(ctx context.Context) (result ctrl.Result, err error) {
		logger := m.logger.WithValues("action", description)

		if m.hook != nil {
			defer func() { m.hook.PostRun(ctx, logger, description, result, err) }()
			m.hook.PreRun(ctx, logger, description, nil)
		}

		return f(ctx, logger)
	})
}

// GrabScaleViewLock generates the action of "GrabScaleViewLock".
func (m *RisingWaveScaleViewControllerManager) GrabScaleViewLock() ctrlkit.Action {
	return ctrlkit.NewAction(RisingWaveScaleViewAction_GrabScaleViewLock, func(ctx context.Context) (result ctrl.Result, err error) {
		logger := m.logger.WithValues("action", RisingWaveScaleViewAction_GrabScaleViewLock)

		// Get states.
		targetObj, err := m.state.GetTargetObj(ctx)
		if err != nil {
			return ctrlkit.RequeueIfError(err)
		}

		// Invoke action.
		if m.hook != nil {
			defer func() { m.hook.PostRun(ctx, logger, RisingWaveScaleViewAction_GrabScaleViewLock, result, err) }()
			m.hook.PreRun(ctx, logger, RisingWaveScaleViewAction_GrabScaleViewLock, map[string]runtime.Object{
				"targetObj": targetObj,
			})
		}

		return m.impl.GrabScaleViewLock(ctx, logger, targetObj)
	})
}

// SyncGroupReplicasToRisingWave generates the action of "SyncGroupReplicasToRisingWave".
func (m *RisingWaveScaleViewControllerManager) SyncGroupReplicasToRisingWave() ctrlkit.Action {
	return ctrlkit.NewAction(RisingWaveScaleViewAction_SyncGroupReplicasToRisingWave, func(ctx context.Context) (result ctrl.Result, err error) {
		logger := m.logger.WithValues("action", RisingWaveScaleViewAction_SyncGroupReplicasToRisingWave)

		// Get states.
		targetObj, err := m.state.GetTargetObj(ctx)
		if err != nil {
			return ctrlkit.RequeueIfError(err)
		}

		// Invoke action.
		if m.hook != nil {
			defer func() {
				m.hook.PostRun(ctx, logger, RisingWaveScaleViewAction_SyncGroupReplicasToRisingWave, result, err)
			}()
			m.hook.PreRun(ctx, logger, RisingWaveScaleViewAction_SyncGroupReplicasToRisingWave, map[string]runtime.Object{
				"targetObj": targetObj,
			})
		}

		return m.impl.SyncGroupReplicasToRisingWave(ctx, logger, targetObj)
	})
}

// SyncGroupReplicasStatusFromRisingWave generates the action of "SyncGroupReplicasStatusFromRisingWave".
func (m *RisingWaveScaleViewControllerManager) SyncGroupReplicasStatusFromRisingWave() ctrlkit.Action {
	return ctrlkit.NewAction(RisingWaveScaleViewAction_SyncGroupReplicasStatusFromRisingWave, func(ctx context.Context) (result ctrl.Result, err error) {
		logger := m.logger.WithValues("action", RisingWaveScaleViewAction_SyncGroupReplicasStatusFromRisingWave)

		// Get states.
		targetObj, err := m.state.GetTargetObj(ctx)
		if err != nil {
			return ctrlkit.RequeueIfError(err)
		}

		// Invoke action.
		if m.hook != nil {
			defer func() {
				m.hook.PostRun(ctx, logger, RisingWaveScaleViewAction_SyncGroupReplicasStatusFromRisingWave, result, err)
			}()
			m.hook.PreRun(ctx, logger, RisingWaveScaleViewAction_SyncGroupReplicasStatusFromRisingWave, map[string]runtime.Object{
				"targetObj": targetObj,
			})
		}

		return m.impl.SyncGroupReplicasStatusFromRisingWave(ctx, logger, targetObj)
	})
}

// HandleScaleViewFinalizer generates the action of "HandleScaleViewFinalizer".
func (m *RisingWaveScaleViewControllerManager) HandleScaleViewFinalizer() ctrlkit.Action {
	return ctrlkit.NewAction(RisingWaveScaleViewAction_HandleScaleViewFinalizer, func(ctx context.Context) (result ctrl.Result, err error) {
		logger := m.logger.WithValues("action", RisingWaveScaleViewAction_HandleScaleViewFinalizer)

		// Get states.
		targetObj, err := m.state.GetTargetObj(ctx)
		if err != nil {
			return ctrlkit.RequeueIfError(err)
		}

		// Invoke action.
		if m.hook != nil {
			defer func() { m.hook.PostRun(ctx, logger, RisingWaveScaleViewAction_HandleScaleViewFinalizer, result, err) }()
			m.hook.PreRun(ctx, logger, RisingWaveScaleViewAction_HandleScaleViewFinalizer, map[string]runtime.Object{
				"targetObj": targetObj,
			})
		}

		return m.impl.HandleScaleViewFinalizer(ctx, logger, targetObj)
	})
}

type RisingWaveScaleViewControllerManagerOption func(*RisingWaveScaleViewControllerManager)

func RisingWaveScaleViewControllerManager_WithActionHook(hook ctrlkit.ActionHook) RisingWaveScaleViewControllerManagerOption {
	return func(m *RisingWaveScaleViewControllerManager) {
		m.hook = hook
	}
}

// NewRisingWaveScaleViewControllerManager returns a new RisingWaveScaleViewControllerManager with given state and implementation.
func NewRisingWaveScaleViewControllerManager(state RisingWaveScaleViewControllerManagerState, impl RisingWaveScaleViewControllerManagerImpl, logger logr.Logger, opts ...RisingWaveScaleViewControllerManagerOption) RisingWaveScaleViewControllerManager {
	m := RisingWaveScaleViewControllerManager{
		state:  state,
		impl:   impl,
		logger: logger,
	}

	for _, opt := range opts {
		opt(&m)
	}

	return m
}
