name: CI

on:
  pull_request:
    types: [review_requested, ready_for_review, synchronize, reopened]
    branches:
    - main
  push:
    branches:
    - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.50.1
          args: --config .golangci.yaml
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Check out code
        uses: actions/checkout@v2
      - name: unit-test
        run: |
          make test
      - uses: codecov/codecov-action@v3
        name: Upload the codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./cover.out
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
