name: Build of risingwave-minio image

on:
  pull_request:
    types: [review_requested, ready_for_review]
    paths:
      - '.github/workflows/docker_build_minio.yml'
      - 'docker/minio/Dockerfile'
      - 'scripts/set_minio.sh'

  # For manually triggering workflow
  workflow_dispatch:

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build risingwave-minio
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/minio/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/singularity-data/risingwave-minio
