name: License Checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  license-header-check:
    runs-on: ubuntu-latest
    name: license-header-check
    steps:
    - uses: actions/checkout@v2
    - name: Check License Header
      uses: apache/skywalking-eyes/header@501a28d2fb4a9b962661987e50cf0219631b32ff
