name: Release Pipeline

on:
  release:
    types: [ published ]

jobs:
  build-and-upload-manifests:
    name: build-and-upload-manifests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: 1.21
    - run: make generate-yaml TAG="${{ github.ref_name }}"
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: config/risingwave-operator.yaml